import { ProtectedPage } from "@/components/ProtectedPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bot-Hits | CRM Pogodka",
  description: "Generated by create next app",
};

export default function BotHitsPage() {
  return (
    <ProtectedPage allowedRoles={["admin", "editor"]}>
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        <div className="grid auto-rows-min gap-4 md:grid-cols-3">
          <div className="bg-muted/50 aspect-video rounded-xl">
            <h1>BotHits</h1>
          </div>
        </div>
      </div>
    </ProtectedPage>
  );
}
