import { ProtectedPage } from "@/components/ProtectedPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Banned | CRM Pogodka",
  description: "Generated by create next app",
};

export default function BannedPage() {
  return (
    <ProtectedPage allowedRoles={["admin"]}>
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        <div className="grid auto-rows-min gap-4 md:grid-cols-3">
          <h1>banned</h1>
        </div>
      </div>
    </ProtectedPage>
  );
}
